Feature/login layout
wecode-bootcamp-korea/41-1st-GGogi-frontend pull request #1
Opened 2023-01-03 05:31 UTC by dalsong00

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 로그인 화면 레이아웃 완성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
 - scss와 Mixin을 활용하여 로그인 화면 구현
 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2023-01-03 05:58 UTC, hani2525 requested changes
리뷰 확인하고 반영해주세요! 👍

2023-01-03 05:58 UTC, hani2525 commented on public/index.html
> +      rel="stylesheet"
`index.html`파일에 들어가는 폰트 설정은 다른 프론트 팀원과 협의가 된 내용인가요?

2023-01-03 05:58 UTC, hani2525 commented on src/pages/Login/Login.js
> +  };
사용하지 않는 주석은 지워주시고 추후에 사용될 코드를 주석 처리할 때는 아래와 같이 TODO를 활용해주시면 좋습니다.

`//TODO: (아직 하지 않은 일을 작성해주세요)`

2023-01-03 05:58 UTC, hani2525 commented on src/pages/Login/Login.js
> +          {/* 회원가입 */}
이 부분도 마찬가지로 TODO 주석을 활용해주세요 :)

2023-01-03 05:58 UTC, hani2525 commented on src/pages/Login/Login.scss
> +  }
최상위 classname 안에서 전체 CSS 스타일링을 주셨네요.
로그인 컴포넌트에서 전체적으로 스타일링을 하고 싶을 때
최상위 태그에 스타일링을 지정해주세요.

2023-01-03 05:59 UTC, hani2525 commented
PR 제목 양식은 아래와 같이 작성해주시면 됩니다. 확인 후 수정해주세요~! 

**[41기 홍길동] ADD : 기능에 대한 간략한 설명**

2023-01-03 07:04 UTC, dalsong00 commented on public/index.html
> +      rel="stylesheet"
네!! main branch에서 common.scss 내용 추가 후 push 하려고 했는데 막혀있어서 각자 common.scss에 동일한 내용을 추가하기로 했습니다.

2023-01-03 07:05 UTC, sstaar91 reviewed
지수님 추가로 수정사항 반영해주세요!

2023-01-03 07:05 UTC, sstaar91 commented on src/styles/common.scss
>  }
해당 코드는 variables.scss에서 적용되어야 하는 코드입니다.
파일이 없다면 styles 폴더에 파일 생성해서 작성해주세요

2023-01-04 01:21 UTC, hani2525 commented
LGTM 고생하셨습니다! 지수님! ❤️

2023-01-04 01:21 UTC, hani2525 approved these changes

2023-01-04 01:21 UTC, merged