[41기 하평안] Mypage 상단 레이아웃 구현 완료
wecode-bootcamp-korea/41-1st-GGogi-frontend pull request #13
Opened 2023-01-05 05:47 UTC by 96smilepeace

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- Mypage 전체 레이아웃 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. Mypage 상단 layout 구현 완료

<br />

## :: 성장 포인트 
-css 지식 상승

<br />

## :: 기타 질문 및 특이 사항

2023-01-05 05:54 UTC, hani2525 requested changes
PR 리뷰 반영해주세요~ 💫

2023-01-05 05:54 UTC, hani2525 commented on src/pages/MyPage/MyPageUserInterface.jsx
> +            </button>
button tag - div tag 이 UI 구조가 많이 반복되네요. 다른 페이지에서도 자주 쓰인다면 팀원들과 상의 후 컴포넌트로 만들면 좋을 것 같습니다. 만약 해당 페이지에서만 쓰인다면 map을 통해 중복되는 코드를 줄일 수 있겠죠?

2023-01-05 05:54 UTC, hani2525 commented on src/pages/MyPage/MyPageUserInterface.scss
> +  }
cursor라는 className을 만들고 스타일을 주는 것보다
button 태그에서 공통적으로 가지고 있는 className에 스타일 속성을 적용하면 필요 이상의 클래스명을 부여하지 않아도 됩니다.

2023-01-05 08:41 UTC, 96smilepeace commented on src/pages/MyPage/MyPageUserInterface.scss
> +  }
반영 했습니다.

2023-01-05 08:42 UTC, 96smilepeace commented on src/pages/MyPage/MyPageUserInterface.jsx
> +            </button>
반영했습니다!

2023-01-06 02:18 UTC, hani2525 requested changes
평안님 고생하셨습니다! PR 리뷰 확인 후 반영해주세요! 곧 머지가 머지않음 👀

2023-01-06 02:18 UTC, hani2525 commented on src/pages/MyPage/MyPage.js
> +    </div>
MyPage 컴포넌트에서 딱 하나의 자식 컴포넌트만 렌더링하기 때문에 감싸주는 태그(div)는 없어도 됩니다.

2023-01-06 02:18 UTC, hani2525 commented on src/pages/MyPage/MyPageUserInterface.jsx
> +                컬리 퍼플 박스<span className="spanArrowColor"> ></span>
닫는 태그가 하나 잘못 들어간 것 같네요~ 확인해주세요

2023-01-06 02:18 UTC, hani2525 commented on src/pages/MyPage/MyPageUserInterface.scss
> +    // flex: 1;
주석은 지워주세요~

2023-01-06 03:58 UTC, 96smilepeace commented on src/pages/MyPage/MyPageUserInterface.jsx
> +                컬리 퍼플 박스<span className="spanArrowColor"> ></span>
화살표를 저렇게 표현하려 했는데 fontawesome으로 변환했습니다.

2023-01-06 03:58 UTC, 96smilepeace commented on src/pages/MyPage/MyPageUserInterface.scss
> +    // flex: 1;
주석 삭제 했습니다!

2023-01-06 04:33 UTC, 96smilepeace commented on src/pages/MyPage/MyPage.js
> +    </div>
수정 했습니다.

2023-01-06 05:45 UTC, hani2525 approved these changes
LGTM! 고생 많으셨습니다 🎉

2023-01-06 05:45 UTC, merged