[41기 하평안] 마이페이지 버튼 구현, 버튼 클릭시 화면 랜더링 구현 완료
wecode-bootcamp-korea/41-1st-GGogi-frontend pull request #15
Opened 2023-01-06 07:01 UTC by 96smilepeace

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
-화면 랜더링 되는 컴포넌트 내부 통신, ui 작업

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 마이페이지 내부 사용될 버튼 컴포넌트 생성
2. 버튼 컴포넌트 상수데이터, map을 사용하여 랜더링 (ui 작업 완료)
3. 버튼 클릭시 화면에 표시될 컴포넌트 생성
4. usestate 끌어올리기를 사용하여 버튼 클릭시 화면에 랜더링

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- usestate로 함수를 props로 주어 상위 컴포넌트의 상태값을 변경

<br />

## :: 기타 질문 및 특이 사항

2023-01-06 09:00 UTC, hani2525 requested changes
PR리뷰 확인해주세요!

2023-01-06 09:55 UTC, 96smilepeace commented on src/pages/MyPage/MyPage.js
> +import { useState } from 'react';
수정완료 했습니다.

2023-01-06 09:55 UTC, 96smilepeace commented on src/pages/MyPage/components/MypageBtn.jsx
> +  const [clickevent, setClickevent] = useState({ state: false });
수정했습니다.

2023-01-09 10:02 UTC, hani2525 requested changes
PR리뷰 반영해주세요~

2023-01-10 00:13 UTC, 96smilepeace commented on src/pages/MyPage/MyPage.js
> +import MypageAddress from './components/MypageAddress';
확인 했습니다!

2023-01-10 00:14 UTC, 96smilepeace commented on src/pages/MyPage/MypageCategory.jsx
> +        {MAINPAGELIST.map((item) => {
수정 완료

2023-01-10 00:22 UTC, 96smilepeace commented on src/pages/MyPage/components/MypageUserInfo.jsx
> +        body: JSON.stringify({ password: 'confirmPwdagain' }),
수정 완료

2023-01-10 00:22 UTC, 96smilepeace commented on src/pages/MyPage/components/MypageOrder.scss
> +
수정 완료

2023-01-10 00:22 UTC, 96smilepeace commented on src/pages/MyPage/components/MypageOrder.scss
> +      padding: 0 0 35px 0;
수정 완료

2023-01-10 00:22 UTC, 96smilepeace commented on src/pages/MyPage/components/MypageBtn.jsx
> +      SetChangedBtnColor(!changedBtnColor);
수정 완료

2023-01-10 00:22 UTC, 96smilepeace commented on src/pages/MyPage/components/MypageAddress.jsx
> +import { AiOutlineCheck } from 'react-icons/ai';
수정 완료

2023-01-10 00:22 UTC, 96smilepeace commented on src/pages/MyPage/MypageCategory.scss
> +    padding: 0 20px 0 20px;
수정 완료

2023-01-10 01:10 UTC, 96smilepeace commented on src/pages/MyPage/components/MypageOrder.jsx
> +                  </div>
혹시 이부분  벡엔드랑 의견이 아직 조율이 되지않아서 오늘 통신하며 map으로 전환할 계획이였는데 개선해서 다음 PR에 적용해봐도 될까요?? 절대 하기 싫어서가 아니라 map으로 전환 후 통신하는 데이터로 전환하는데 어려움이있어서요..

2023-01-10 06:02 UTC, hani2525 approved these changes
LGTM! 고생하셨습니다 🚀

2023-01-10 06:44 UTC, merged