[41기 윤지수] Add : payment 페이지 레이아웃 구현
wecode-bootcamp-korea/41-1st-GGogi-frontend pull request #16
Opened 2023-01-08 12:42 UTC by dalsong00

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 결제 화면 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
* 주문 상품 화살표 버튼 클릭 시 구입 예정인 상품 개수 또는 상품 리스트 나오게 하기
* 결제 금액 창 position: sticky 로 특정 영역에서만 움직이게 하기
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
* PaymentAmount 컴포넌트가 화면의 오른쪽에 위치하면서, 500px 정도만 스크롤이 되도록 하기 위해 부모요소에  position: absolute를, 자식요소에 position: sticky 를 부여했습니다. 컴포넌트를 div로 감싸고 position 속성을 활용하여 다소 복잡한 레이아웃을 구현할 수 있다는 점을 배웠습니다!
* 전체적인 틀(제목과 border-bottom: 1px solid black;)이 반복되니 틀을 만들고 그 안에 내용을 다르게 채워넣으면 좋았을듯합니다. 
   
<br />

## :: 기타 질문 및 특이 사항

2023-01-09 10:18 UTC, hani2525 requested changes
PR리뷰 확인해주세요~

2023-01-09 10:18 UTC, hani2525 commented on src/pages/Payment/component/ordererInfo/OrdererInfo.js
> +        })}
item에서 쓰일 데이터 구조분해할당 해서 가져올 수 있겠죠?

2023-01-09 10:18 UTC, hani2525 commented on src/pages/Payment/component/ordererInfo/OrdererInfo.scss
> +  justify-content: center;
해당코드는 다른 분들도 자주 사용하시는 스타일 속성인 것 같은데 mixin 사용해보시는 걸 추천드립니다.

2023-01-10 01:36 UTC, dalsong00 commented on src/pages/Payment/component/ordererInfo/OrdererInfo.scss
> +  justify-content: center;
안녕하세요! align-items까지 있어야 단축속성으로 쓸 수 있게 템플릿을 만들어놔서 다음에 써보겠습니다!

2023-01-10 05:24 UTC, hani2525 commented
충돌 resolve 한 뒤에 push 해주세요 :)

2023-01-10 05:45 UTC, hani2525 approved these changes
LGTM! 고생하셨습니다 💫

2023-01-10 05:45 UTC, merged