[41기 하평안] Nav 기능 추가, 레이아웃 수정
wecode-bootcamp-korea/41-1st-GGogi-frontend pull request #19
Opened 2023-01-09 09:35 UTC by 96smilepeace

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. nav 카테고리 배너 추가
2. nav 레이아웃 조정
3. nav 경로 설정

4. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2023-01-09 10:46 UTC, hani2525 requested changes
리뷰 반영해주세요~

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navcategory.jsx
> +  const [scrollSubActive, setScrollSubActive] = useState(true);
- 유사한 속성의 state는 하나의 객체로 할당해주시면 훨씬 더 코드가 간결하고 관리에 용이합니다. 아래 예시 코드를 참조해주세요.
    
    ```jsx
    // bad
    const [isLocationActive, setIsLocationActive] = useState(false);
    const [location, setLocation] = useState("");
    const [isDatesActive, setIsDatesActive] = useState(false);
    const [isGuestActive, setIsGuestActive] = useState(false);
    
    // good
    const [location, setLocation] = useState("");
    const [isActive, setIsActive] = useState({ location: false, date: false, guest: false });
    ```

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navcategory.jsx
> +                {idx + 1 === Number(subCategoryId) && categoeyPoint && (
- 조건문의 조건이 길어지는 경우에는 해당 조건을 변수에 담아 깔끔하게 코드를 작성할 수 있습니다. 아래를 참고해주세요.

```jsx
function onLogin(){
  const user = userId.value;
  const passwod = userPassword.value;

	const isUserInfoValid = user.length > 5 && password.length > 5;

	if(isUserInfoValid) {
		// A
	}

}
```

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navcategory.jsx
> +              {item.name}
item에서 구조분해 할당 사용하면 더 깔끔하겠죠?

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navcategory.scss
> +  background-color: white;
- 하나의 요소에 여러가지 속성을 부여하는 경우 중요도, 관련도에 따라 나름의 convention을 지켜서 작성하는 것이 좋습니다.
- 일반적인 convention 은 아래와 같습니다. 아래와 같이 순서 적용해주세요.
    
    [CSS property 순서]
    
    - Layout Properties (position, float, clear, display)
    - Box Model Properties (width, height, margin, padding)
    - Visual Properties (color, background, border, box-shadow)
    - Typography Properties (font-size, font-family, text-align, text-transform)
    - Misc Properties (cursor, overflow, z-index)

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navcategory.scss
> +    align-items: center;
이 부분 variable.scss에서 mixin 선언하신 것 같은데 사용하시면 좋을 것 같습니다.

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navcategory.scss
> +  }
className으로 관리해주시면 한 번에 스타일 적용할 수 있겠죠?

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navcategory.scss
> +    display: inline-block;
CSS 속성 순서 변경해주세요~

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navcategory.scss
> +    align-items: center;
여기도 mixin 사용해주세요~!

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navcategory.scss
> +  }
이 부분 위 코드랑 중복되네요 확인 한 번 해주세요~

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navcategory.scss
> +.sideCategory:hover .middleCategory {
hover시에 속성을 변경해주는 이유가 뭔가요~?

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navloginsignup.jsx
> +import { useNavigate } from 'react-router-dom';
import 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 이런 컨벤션 준수들이 모여서 좀 더 가독성 좋은 코드가 됩니다. Refactoring Checklist 및 아래의 순서 참고해주세요.

- 라이브러리
    - React 관련 패키지
    - 외부 라이브러리
- 컴포넌트
    - 공통 컴포넌트 → 먼 컴포넌트 → 가까운 컴포넌트
- 함수, 변수 및 설정 파일
- 사진 등 미디어 파일(`.png`)
- css 파일 (.`scss`)

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navloginsignup.jsx
> +      {localStorage.getItem('Token') && (
localStorage.getItem('token') 이 부분을 변수화 시켜서 앞에서 선언 및 할당해주고 코드에서는 변수를 사용할 수 있게 해주는게 가독성이 더 좋을 것 같습니다.

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navloginsignup.jsx
> +        <button className="signup " onClick={goToMypage}>
클래스명에 띄어쓰기 있는 것 같은데 확인 한 번 해주세요!

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navloginsignup.jsx
> +      {localStorage.getItem('Token') == undefined && (
`localStorage.getItem('Token') == undefined` => 이것도 변수화 시켜서 사용하면 코드가 더 깔끔하겠죠?

2023-01-09 10:46 UTC, hani2525 commented on src/components/Nav/Navsearchline.jsx
>  import Cart from '../../assets/images/shoppingCart.png';
import 순서 맞춰주세요~

2023-01-09 12:34 UTC, 96smilepeace commented on src/components/Nav/Navsearchline.jsx
>  import Cart from '../../assets/images/shoppingCart.png';
수정 완료

2023-01-09 12:38 UTC, 96smilepeace commented on src/components/Nav/Navloginsignup.jsx
> +      {localStorage.getItem('Token') == undefined && (
수정 완료

2023-01-09 12:39 UTC, 96smilepeace commented on src/components/Nav/Navloginsignup.jsx
> +        <button className="signup " onClick={goToMypage}>
수정 완료

2023-01-09 12:41 UTC, 96smilepeace commented on src/components/Nav/Navloginsignup.jsx
> +      {localStorage.getItem('Token') && (
수정 완료

2023-01-09 12:41 UTC, 96smilepeace commented on src/components/Nav/Navloginsignup.jsx
> +import { useNavigate } from 'react-router-dom';
수정 완료

2023-01-09 12:43 UTC, 96smilepeace commented on src/components/Nav/Navcategory.scss
> +    align-items: center;
수정 완료

2023-01-09 12:58 UTC, 96smilepeace commented on src/components/Nav/Navcategory.scss
> +  background-color: white;
수정 완료

2023-01-09 13:11 UTC, 96smilepeace commented on src/components/Nav/Navcategory.jsx
> +              {item.name}
수정 완료

2023-01-09 23:50 UTC, 96smilepeace commented on src/components/Nav/Navcategory.jsx
> +  const [scrollSubActive, setScrollSubActive] = useState(true);
수정 했습니다.

2023-01-10 06:30 UTC, 96smilepeace commented on src/components/Nav/Navcategory.scss
> +    align-items: center;
수정 완료

2023-01-10 06:31 UTC, 96smilepeace commented on src/components/Nav/Navcategory.scss
> +    display: inline-block;
수정 완료

2023-01-10 08:20 UTC, hani2525 approved these changes
평안님 고생하셨습니다 :) 우선 기능적으로 완성하시고 CSS 리뷰는 추후에 반영해주세요!

2023-01-10 08:20 UTC, merged