[41기 하평안] Add : Footer 레이아웃 작업 완료
wecode-bootcamp-korea/41-1st-GGogi-frontend pull request #8
Opened 2023-01-04 04:27 UTC by 96smilepeace

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2023-01-04 05:38 UTC, hani2525 requested changes

2023-01-04 05:38 UTC, hani2525 commented on src/components/Footer/FooterLayout.scss
> +}
이 부분은 common.scss에서 이미 선언하셔서 모든 파일에 적용이 됩니다. 중복 사용하지 않게 유의해주세요~

2023-01-04 05:38 UTC, hani2525 commented on src/components/Footer/FooterLayout.scss
> +  .footerLayout {
가독성을 위해 한 줄 띄기 해주세요.

2023-01-04 05:38 UTC, hani2525 commented on src/components/Footer/FooterLayout.scss
> +      justify-content: space-between;
이 부분 variable.scss에서 mixin으로 선언하셨는데 한 번 확인해주세요~

2023-01-04 05:38 UTC, hani2525 commented on src/components/Footer/FooterLayout.scss
> +          margin-bottom: 15px;
- 하나의 요소에 여러가지 속성을 부여하는 경우 중요도, 관련도에 따라서 나름의 convention을 지켜서 작성하는 것이 좋습니다.
- 일반적인 convention 은 아래와 같습니다. 아래와 같이 순서 적용해주세요.
    
    [CSS property 순서]
    
    - Layout Properties (position, float, clear, display)
    - Box Model Properties (width, height, margin, padding)
    - Visual Properties (color, background, border, box-shadow)
    - Typography Properties (font-size, font-family, text-align, text-transform)
    - Misc Properties (cursor, overflow, z-index)

2023-01-04 05:38 UTC, hani2525 commented on src/components/Footer/FooterLayout.scss
> +      }
- img 태그 처럼 빈번히 사용되는 태그로 스타일을 주는 건 depth에 무관하게 적용되어 의도치 않은 스타일링이 될 수 있습니다. 클래스 셀렉터(ex. `.foo`)를 사용해주세요.
- tag selector는 해당 요소 뿐만 아니라 동일한 태그로 선언된 다른 요소들에게도 영향을 미칠 여지가 너무 많기 때문에 추후 유지보수에 악영향을 미칠 수 있습니다.
- 스타일링을 줄 때는 요소마다 className을 부여하셔서 스타일링을 주시는게 좋습니다.

2023-01-04 05:38 UTC, hani2525 commented on src/styles/common.scss
> +// }
안쓰시는 주석은 지워주세요~
특히 특정 컴포넌트에서만 적용되어야 하는 스타일링이면 common.scss에서 작성하시면 안됩니다.

2023-01-04 05:38 UTC, hani2525 commented on src/components/Footer/FooterLayout.jsx
> +import partners4 from '../../assets/images/partners4.png';
image를 여러개 가져올 때는 import 하는 부분에서 가져오는 건 가독성이 떨어질 수 있습니다. img 태그 내에서 속성값으로 넣어주세요~

2023-01-04 05:38 UTC, hani2525 commented on src/components/Footer/FooterLayout.jsx
> +              <span className="leftFooterText3">
클래스명 네이밍을 foo1,foo2,foo3 이런 식으로 넘버링을 하는 것은 좋은 습관이 아닙니다.
해당 태그의 내용과 특징을 알아볼 수 있는 이름으로 정정해주세요.

2023-01-04 05:38 UTC, hani2525 commented on src/components/Footer/FooterLayout.jsx
> +              <img src={youtube} alt="youtubeimg" />
alt 속성은 스크린 리더기 또는 img에 오류가 있을 때 화면에 보여주는 정보입니다. 띄어쓰기 해주세요~

2023-01-04 05:38 UTC, hani2525 commented on src/components/Footer/FooterLayout.jsx
> +                  <li className={item.id}>{item.text}</li>
map을 돌릴 때 key값도 추가해줘야겠죠? Key값 추가해주세요~

2023-01-04 05:39 UTC, hani2525 commented
평안님 ~ 고생하셨습니다 :) PR 리뷰 확인해주시고 반영해주세요! 그리고 리뷰 반영한 PR 올리기 전에 충돌한 부분 확인해주시고 resolve 해주세요~

2023-01-04 06:09 UTC, sstaar91 reviewed
평안님 수고하셨습니다.
아직 하은님 리뷰 반영이 안된 상태로 라벨 변경하신거 같은데
리뷰 사항 반영해 주지 않으시면 merge 되지 않으니
수정 사항 반영해 주신 다음 다시 라벨 변경해주세요~

2023-01-04 06:09 UTC, sstaar91 commented on src/Router.js
> +      <Footer path="Footer" element={<Footer />} />
```suggestion
      <Footer />
```
footer는 모든 페이지에서 보여야 하는 컴포넌트기 때문에
경로를 지정해 주지 않아도 됩니다!

2023-01-04 06:09 UTC, sstaar91 commented on src/components/Footer/FooterLayout.jsx
> +          </div>
UI가 중복으로 적용되어있는 부분이네요!
상수데이터와 map 메서드를 활용해서 구현해주세요!

2023-01-04 08:27 UTC, 96smilepeace commented on src/components/Footer/FooterLayout.jsx
> +                  <li className={item.id}>{item.text}</li>
key 값 할당 했습니다

2023-01-04 08:28 UTC, 96smilepeace commented on src/components/Footer/FooterLayout.scss
> +}
pull한 후 삭제했습니다.

2023-01-04 08:28 UTC, 96smilepeace commented on src/components/Footer/FooterLayout.scss
> +  .footerLayout {
띄어쓰기 완료했습니다!

2023-01-04 08:29 UTC, 96smilepeace commented on src/components/Footer/FooterLayout.scss
> +          margin-bottom: 15px;
전체적으로 순서에 맞게 수정했습니다.

2023-01-04 08:29 UTC, 96smilepeace commented on src/components/Footer/FooterLayout.scss
> +      }
클래스명으로 주었습니다!

2023-01-04 08:30 UTC, 96smilepeace commented on src/components/Footer/FooterLayout.jsx
> +              <img src={youtube} alt="youtubeimg" />
띄어쓰기 완료했습니당 img -> logo로 변경

2023-01-04 08:31 UTC, 96smilepeace commented on src/Router.js
> +      <Footer path="Footer" element={<Footer />} />
경로 수정 완료했습니다!

2023-01-04 09:42 UTC, 96smilepeace commented on src/components/Footer/FooterLayout.jsx
> +              <span className="leftFooterText3">
수정 완료했습니다.

2023-01-04 09:42 UTC, 96smilepeace commented on src/components/Footer/FooterLayout.jsx
> +          </div>
상수데이터와 map 으로 변경 완료했습니다.

2023-01-04 09:44 UTC, 96smilepeace commented on src/components/Footer/FooterLayout.jsx
> +import partners4 from '../../assets/images/partners4.png';
수정 완료했습니다.

2023-01-05 01:55 UTC, hani2525 requested changes

2023-01-05 01:55 UTC, hani2525 commented on src/components/Footer/FooterLayout.jsx
> +              </span>
이 부분도 UI가 중복되네요! 상수데이터와 map 메서드를 이용하면 가독성도 좋고 효율적인 코드를 구현할 수 있겠죠?

2023-01-05 01:55 UTC, hani2525 commented on src/components/Footer/FooterLayout.jsx
> +            <br />
반복되는 UI

2023-01-05 01:55 UTC, hani2525 commented on src/components/Footer/FooterLayout.jsx
> +            <span className="footerTimeInfo">오전 7시 ~ 오후 1시</span>
반복되는 UI

2023-01-05 01:55 UTC, hani2525 commented on src/components/Footer/FooterLayout.jsx
> +              <img src="./images/youtube.png" alt="youtube logo" />
반복되는 UI

2023-01-05 02:41 UTC, 96smilepeace commented on src/components/Footer/FooterLayout.jsx
> +            <br />
map 활용 구현 완료

2023-01-05 02:46 UTC, 96smilepeace commented on src/components/Footer/FooterLayout.jsx
> +              <img src="./images/youtube.png" alt="youtube logo" />
map 활용 구현 완료

2023-01-05 02:54 UTC, 96smilepeace commented on src/components/Footer/FooterLayout.jsx
> +              </span>
map 활용 구현 완료

2023-01-05 03:58 UTC, hani2525 approved these changes
LGTM!

2023-01-05 03:58 UTC, merged