[41기 박예솔 ] Add : shopping Modal  레이아웃 구현 완료
wecode-bootcamp-korea/41-1st-GGogi-frontend pull request #9
Opened 2023-01-04 08:36 UTC by yessssssssssol

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인 페이지에서 상품을 보고 쇼핑 카트에  간단하게 넣을 수 있는 쇼핑 모달창을 구현했습니다.
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 메인에 노출되는 상품 카드에 쇼핑카트 버튼을 누르면 뜨게 될 상품 장바구니 담기 모달창을 구현했습니다.
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 모달창이 뜨게 되면 모달 창 외에 배경을 흐리게 하고 싶음
  - 실패 과정 : body 또는 id = 'root'에 opacity를 추가했는데 모달창도 흐려져서 실패
  - 해결 방법 :  모달창의 그림자를 크게 주어 배경을 흐리게 만들 수 있었습니다!

<br />

## :: 기타 질문 및 특이 사항

2023-01-04 08:50 UTC, hani2525 requested changes
예솔님 고생하셨습니다! 리뷰 확인해주시고 반영해주세요!
그리고 스타일 속성 순서가 섞여있네요 스타일 속성 순서에 맞춰 다시 변경해주세요~ 😚

2023-01-04 08:50 UTC, hani2525 commented on src/components/PlusMinusBtn/PlusMinusBtn.scss
> +    text-align: center;
- 하나의 요소에 여러가지 속성을 부여하는 경우 중요도, 관련도에 따라서 나름의 convention을 지켜서 작성하는 것이 좋습니다.
    - 일반적인 convention 은 아래와 같습니다. 아래와 같이 순서 적용해주세요.
        
        [CSS property 순서]
        
        - Layout Properties (position, float, clear, display)
        - Box Model Properties (width, height, margin, padding)
        - Visual Properties (color, background, border, box-shadow)
        - Typography Properties (font-size, font-family, text-align, text-transform)
        - Misc Properties (cursor, overflow, z-index)

2023-01-04 08:50 UTC, hani2525 commented on src/components/ShoppingModal/ShoppingModal.scss
> +  box-shadow: 0 0 0 9999px rgb(0 0 0 / 15%);
여기도 CSS 속성 순서 맞춰주세요~

2023-01-04 08:50 UTC, hani2525 commented on src/components/ShoppingModal/ShoppingModal.scss
> +      }
스타일 관련 코드가 없으면 삭제해주세요!

2023-01-04 08:50 UTC, hani2525 commented on src/components/ShoppingModal/ShoppingModal.js
> +          <span className="shoppingModalPrice">29,000원</span>
여기서 가격은 span 태그를 사용했고 18번째줄에서 가격은 div태그를 사용했는데 다르게 사용하신 이유가 있나요?

2023-01-04 09:12 UTC, yessssssssssol commented on src/components/ShoppingModal/ShoppingModal.js
> +          <span className="shoppingModalPrice">29,000원</span>
제가 다른 속성을 지우고 가격으로 변경하다가 다르게 적용됐습니다. 수정하겠습니다!

2023-01-05 01:57 UTC, hani2525 approved these changes
고생하셨습니다 예솔님! :) LGTM 💌

2023-01-05 01:57 UTC, merged